version: "3.3"
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  nginx:
    image: openlmis/nginx:${OL_NGINX_VERSION}
    ports:
      - "${OL_HTTP_PORT:-80}:80"
    env_file: settings.env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on: [consul]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  reference-ui:
    #image: openlmis/reference-ui:${OL_REFERENCE_UI_VERSION}
    image: ghcr.io/emaginacion/openlmis_es_gt_ui:latest
    env_file: settings.env
    depends_on: [consul]
    mem_limit: '1.3G'
    cpus: 2
    volumes:
      - './config/reference-ui/default.conf:/etc/nginx/conf.d/default.conf'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  requisition:
    image: openlmis/requisition:${OL_REQUISITION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    mem_limit: '1.3G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  referencedata:
    image: openlmis/referencedata:${OL_REFERENCEDATA_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    mem_limit: '1.3G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  auth:
    image: openlmis/auth:${OL_AUTH_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    mem_limit: '0.7G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  notification:
    image: openlmis/notification:${OL_NOTIFICATION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    mem_limit: '0.7G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  fulfillment:
    image: openlmis/fulfillment:${OL_FULFILLMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    mem_limit: '0.7G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  cce:
    image: openlmis/cce:${OL_CCE_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    mem_limit: '0.7G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  stockmanagement:
    image: openlmis/stockmanagement:${OL_STOCKMANAGEMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    mem_limit: '0.7G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  report:
    image: openlmis/report:${OL_REPORT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    mem_limit: '0.7G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  buq:
    image: openlmis/buq:${OL_BUQ_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [ log, db ]
    command: [ "/wait-for-postgres.sh", "/run.sh" ]
    mem_limit: '1.3G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  hapifhir:
    restart: always
    image: openlmis/hapifhir:${OL_HAPIFHIR_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    mem_limit: '0.7G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  diagnostics:
    image: openlmis/diagnostics:${OL_DIAGNOSTICS_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]
    mem_limit: '0.7G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  dhis2-integration:
    image: openlmis/dhis2-integration:${OL_DHIS2INTEGRATION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]
    mem_limit: '0.7G'
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  db:
    image: openlmis/postgres:${OL_POSTGRES_VERSION}
    command: postgres -c 'max_connections=1000'
    volumes:
       - ./data:/var/lib/postgresql/data
     # - ./data/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
     # - ./data/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
    env_file: settings.env
    networks:
      default:
        aliases:
          - olmis-db
    depends_on: [consul]
    mem_limit: '1.3G'
    cpus: 4
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  log:
    image: openlmis/rsyslog:${OL_RSYSLOG_VERSION}
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - service-configuration
      - consul
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  service-configuration:
    build:
      context: ./config
    volumes:
      - service-config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ftp:
    image: driesva/proftpd
    ports:
      - "${OL_FTP_PORT_21:-21}:21"
      - "${OL_FTP_PORT_20:-20}:20"
    env_file: settings.env
    depends_on: [consul]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  redis:
    image: redis:3.2.12
    depends_on: [consul]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

volumes:
  syslog:
    external: false
  nginx-log:
    external: false
  consul-template-log:
    external: false
  service-config:
    external: false
